platform :ios, '10.0'

target 'iOSInterviewApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Moya'

  target 'iOSInterviewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSInterviewAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
